### ISSUE TITLE
Error when compiling PID_IC

### ISSUE THREAD

**Issue by Kenny4487** [Tellicious/ArduPID-Library#2]
Compiling (Arduino Nano) the provided example "Standard_PID" creates following error:

`...\Arduino\libraries\ArduPID\PID_IC.cpp: In member function 'virtual void PID_IC::Compute(float)':`
`...\Arduino\libraries\ArduPID\PID_IC.cpp:39:17: error: 'ki' was not declared in this scope`
`   float d_int = ki * e;`
`                 ^`
`exit status 1`

**Comment by Kenny4487** [comment]
i dont know much about libraries but maybe it should be "_ki" instead of "ki"

**Comment by Tellicious** [comment]
It seems like it is just a typo. I’ll look into this as soon as possible

Thanks

Andrea

**Comment by Tellicious** [comment]
Corrected and committed the correct version
