### ISSUE TITLE
"This library only supports boards with an AVR or SAM processor."

### ISSUE THREAD

**Issue by A-Shot** [Tellicious/ArduPID-Library#3]
Hi I'm trying to use it on Teensy 3.2 and getting an error message "This library only supports boards with an AVR or SAM processor."
Is it possible to use it on ARM Cortex M4 processor??

**Comment by A-Shot** [comment]
Hi I'm trying to use it on Teensy 3.2 and getting an error message "This library only supports boards with an AVR or SAM processor."
Is it possible to use it on ARM Cortex M4 processor??

**Comment by A-Shot** [comment]
Hi I'm trying to use it on Teensy 3.2 and getting an error message "This library only supports boards with an AVR or SAM processor."
Is it possible to use it on ARM Cortex M4 processor??

**Comment by zombodotcom** [comment]
Have you tried looking at this thing?

http://playground.arduino.cc/Code/PIDLibrary

https://github.com/br3ttb/Arduino-PID-Library/

**Comment by A-Shot** [comment]
Thats what I’m using right now in my project.I’m building glider with autopilot system,i inspired by this guy https://www.youtube.com/watch?v=U6PQD6Xdg0g.
Im not a pro, so i’m having hard time with PID tuning,I was looking for some self tunning PID.I’m not even sure if PID is right choice for this project.
Any advice or guidance would be greatly appreciated. 

Best,
Josh.
Here are some images of my work

**Comment by zombodotcom** [comment]
https://www.instructables.com/id/Intro-to-Model-Airplane-Autopilot/

**Comment by Tellicious** [comment]
I removed the dependency on Arduino libraries by including stdint. Now it should work fine also on other platforms. Anyway I never implemented self-tuning, as I was targeting high-performance and self-tuning algorithms are always acceptable, often good but never the best.

**Comment by A-Shot** [comment]
Thank you so much.I'm cad designers if you need any 3d model let me know.
