### ISSUE TITLE
PascalCase to camelCase ?

### ISSUE THREAD

**Issue by AurelienConil** [Tellicious/ArduPID-Library#5]
This is not an issue, but more enhancement, but PascalCase is disturbing me. 
Having a Reset() function to call on my PID is not really usual.
Maybe this is a personnal judgement ...

**Comment by Tellicious** [comment]
Hello Aurelien,
I agree that camelCase is more in line with Arduino naming conventions and probably I'll change it in a future commit.

Thanks for the suggestion

**Comment by Tellicious** [comment]
I just had 5 spare minutes and I changed all the code. Didn't have time to test it, though, so feel free to let me know in case of any typo
